### ISSUE TITLE
Improve park visiting behavior (for Park Life DLC)

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#114]
In Park Life DLC, there's 4 types of park, seemingly defined by the UI category of main gate?

* City park
* Amusement Park
* Nature Reserve
* Zoos

As RT gets increasingly sophisticated at planning cim's itinerary, choosing destinations, etc., would it be possible to give different types of park areas their own distinct usage patterns?

I'd jotted down some vague ponders [in this comment](https://github.com/dymanoid/RealTime/issues/65#issuecomment-405747433) on #65.

One issue would be in identifying the park type - main gate UI category could be misleading. For example, I often end up using small city park gates (from workshop) for camp sites or nature reserves rather than the vanilla large nature reserve gates (often not enough space for them where I want to use them).

**Comment by dymanoid** [comment]
Isn't it a part of #86?

**Comment by dymanoid** [comment]
> once RT decides which building to visit, check if it's in a park area. If it is in a park area, cim should try and visit several of the assets within the area.

Actually, this is currently happening already. If a citizen is shopping or having fun **and** it's good time to do it further (no need to go to work, good weather, not too late etc), then the citizen schedules another entertainment or shopping activity.

The only change would be: if a citizen currently visits a park, then try to visit another park asset in the same park area instead of scheduling a random place.
