### ISSUE TITLE
Better understanding of demands

### ISSUE THREAD

**Issue by dymanoid** [dymanoid/RealTime#115]
Since some players report problems with commercial demand, I need a better understanding how it's calculated by the game and how does **Real Time** exactly affect it.
Having that knowledge, it will be possible to decide whether a particular tweak in the citizens logic is required, or maybe the mod's default settings should be changed. In worst case, the code needs to be reworked to play nicely with the vanilla demand code.

**Comment by benzoll37** [comment]
That's right, there is no commercial demand. In addition several shops are not operational (without notice).
I think you asked for a savegame,  new and simple city, with only 22k cims:
https://steamcommunity.com/sharedfiles/filedetails/?id=1450405856

**Comment by aubergine10** [comment]
One thing I considered was should demand calculations be constrained to the period defined by main shift (or, alternatively, wakeup time -> sleep time) rather than whole 24 hours?

**Comment by aubergine10** [comment]
@TMaekler Aren't there info views that show which buildings demand/produce certain things, and also whether they are using internal (from your city) or external (off-map) resources? From vague memory - the natural resources view, and the outside connections view.

You can also use the routes view on a building to get an idea where it's connecting to.

I also find these two mods quite useful for seeing what's going on at district level (although not used them for a few months so not sure if they work with ParkLife or RealTime):

* [District stats](https://steamcommunity.com/sharedfiles/filedetails/?id=1186889659&searchtext=district+resource)
* [District RCI](https://steamcommunity.com/sharedfiles/filedetails/?id=1186900508&searchtext=district+resource)

@dymanoid It would be super-awesome if RealTime could generate district-level stats similar to the two mods above (which are a bit clunky to say the least), as it should be able to provide much better stats due to knowing what the cims are actually doing (eg. where they go shopping on way home for work, which buildings shut at night, and so on).

**Comment by dymanoid** [comment]
This is solved in the [Hotfix 1.8.5](https://github.com/dymanoid/RealTime/releases/tag/1.8.5)
