### ISSUE TITLE
Seems to be incompatible with WG realistic population and consumption mod as well as Ultimate Eyecandy.

### ISSUE THREAD

**Issue by Videonauth** [dymanoid/RealTime#12]
I gave your mod today a trial run over several hours in my well balanced city save. From the start i directly saw that the established demands changed around drastically, from 80% residential demand and about 25% commercial demand and zero industry demand to 30% residential demand and 30% industry demand while commercial demand vanished completely. As i wrote in the title I'm using WG's realistic consumption and population mod. and this city is a model project of mine, it had the same demands for about three days without me changing anything and not expanding the city further as i was working on the network structure to eliminate traffic jams so i know where my city was at. Another issue I found so far is a possible interference from BloodyPinguins Ultimate Eyecandy mod. the times are not in sync and i guess your mod touches the same API parts and there might be an interference. 

As well I can confirm that the demand for commercial sinks so drastically that about 60% of all commercial buildings vanish. Might be even more as i have run the simulation for about 4 hours only.

Beside that a good mod with a lot of potential, even if I will deactivate it for now because of the above mentioned, I really would love to give this a try. Holler if you need any testing.

Right now i run the saved test run without your mod to see if it will recover from that. No worries no harm will be done if not i have extra made a savegame before I tried your mod. Will report here if it will recover or not.

**Comment by Videonauth** [comment]
O.k., another short test run proves, deactivating the mod does not kill a save game, the game will recover from that. However it takes a while running on max speed to recover.

**Comment by dymanoid** [comment]
**Ultimate Eyecandy** conflicts with **Real Time**. But the problem is on the **Ultimate Eyecandy** side - that mod only changes a part of required values in the `SumulationManager`, so the time and date go out of sync with the daytime. Please post an issue on that mod's page if you want to be this fixed. Please note that even after an eventual fix, these mods will still be pretty incompatible. Sudden time leaps will ruin the citizens behavior, the will go crazy.

**Comment by dymanoid** [comment]
Concerning the demand drop: this is caused by a completely different citizens behavior. In the vanilla game, all the citizens were buying and consuming all day and all night long. There are many virtual citizens in the vanilla game, that don't actually move (are teleported from one building to another instantly). The also consume goods. That all makes the demand so high. Don't expect to be the demand the same where suddenly there are significantly less customers (because they are stuck in a traffic jam etc.). This is **Real Time**'s feature. It will always be like that - an existing (large) city will get disbalanced at once if you activate **Real Time** for it. Either create a new city, or make changes to your city to get the things running again.
