### ISSUE TITLE
Power Plants continually run out of fuel

### ISSUE THREAD

**Issue by jmerc** [dymanoid/RealTime#123]
I'm running into an issue where my power plants can't stay fueled.  A shipment arrives, shows 6 weeks of remaining fuel, and within 4 hours (game time) the fuel is used.

The truck is requested from the neighbor city at about 3 weeks of fuel left, but is not able to reach the power plant before fuel runs out completely.

I tested with vanilla coal and oil plants, and I do not have any specialized industry zones in my city yet.

**Comment by aubergine10** [comment]
Just tested this on an old map where I'd used [this asset](https://steamcommunity.com/sharedfiles/filedetails/?id=760376926&searchtext=combined+cycle) and can tentatively confirm - I'm seeing the issue reported above, but I've not tested long enough for simulation to settle so it could be transient issue.

**Comment by benzoll37** [comment]
This is an original game theme.

**Comment by jmerc** [comment]
The issue presented immediately after installing the mod.  The cycle continued 4 times in a row.  Without the mod, the power plants had never indicated they were low on fuel.  With the mod, they ran out of fuel roughly every 4 hours on the in-game clock.

**Comment by dymanoid** [comment]
I really cannot imagine this is caused by **Real Time**. This mod doesn't change the vehicle behavior, the goods/raw material logistics, neither does it affect the power plants by any means.
I see only one possible cause here - there is a weird conflict with some other mod.

To check that, unsubscribe from all other mods temporarily and test with only **Real Time** mod activated. Note that just **disabling** other mods won't do, because many of them still patch the game even when they are "disabled". Ideally, you would purge your Steam mods directory for _Cities:Skylines_ that contains the mods (something like `workshop\content\255710`).

**Comment by aubergine10** [comment]
I think it's more likely that it's just the pants cargo AIs (eg. barely loaded trucks and trains) than anything else. Most likely also happens in vanilla, but vanilla's time chaos and 1-lane traffic jams distract much of the borkage.

**Comment by dymanoid** [comment]
@jmerc, any news about this one?

**Comment by dymanoid** [comment]
Since there's no response from the OP, I'm closing this issue. The problem cannot be reproduced with my test setup, and no one reported a similar issue.
