### ISSUE TITLE
Setting a Time for Public Transportation

### ISSUE THREAD

**Issue by PC28K** [dymanoid/RealTime#126]
I wish I could decide when the first bus leaves and the last bus starts.
Like rush hour, like school time.

**Comment by dymanoid** [comment]
You could control this with other mods, like e.g. **Improved Public Transport 2** or **Transport Lines Manager**.
**Real Time** only changes the time aspect of the city, but not its economy or infrastructure.

**Comment by aubergine10** [comment]
I use IPT2 mod and it's approach is based on day vs. night budget - but it doesn't take in to account that some cims will still be travelling due to long journeys, so it's not really viable to change vehicle quotas using that mod.

I've not used it personally, but looking at the screenshots the TLM mod allows quotas to be set for several time periods throughout the day so give that a try.
