### ISSUE TITLE
City-dweller behavior.

### ISSUE THREAD

**Issue by Everybodyknows** [dymanoid/RealTime#143]
I read a study (about Lyon, France and Montréal, Canada) about the city-dweller behavior. It's very interesting for the future features of real time. There is two elements what I learned :

For summarize : 
the first point is the household structure by urban area. The study point out the repartion of household by citie areas :

Lyon :
![](https://journals.openedition.org/eue/docannexe/image/1054/img-2-small580.png)

Montréal :
![](https://journals.openedition.org/eue/docannexe/image/1054/img-7.png)

Columns Left to right : city centre, rich area around city centre, suburb, rich outskirts.
Lines down to up : Single person, couple without child, couple with child, and... others?

The second point is the repartition of the vehicle  owners or not :

Lyon :
![](https://journals.openedition.org/eue/docannexe/image/1054/img-3-small580.png)

Montréal :
![](https://journals.openedition.org/eue/docannexe/image/1054/img-8-small580.png)

Columns Left to right : city centre, rich area around city centre, suburb, rich outskirts.
Lines down to up : household whitout vehicle, household with one vehicle, household with multi-vehicles.

What do you think about that? Is it possible to implement this? Too difficult ? Useless?

**Comment by dymanoid** [comment]
It's an interesting idea but indeed out of scope for **Real Time**. This mod does only manage the _time_ aspect of the citizens' life. What you're talking about is rather the _social_ aspect.

There are some mods available that somewhat change the social aspect (e.g. **Realistic Population and Consumption**), but I suppose in a very simplified way.

The features you show could be implemented in a separate mod. It doesn't need to be coupled with **Real Time** at all, because it actually can be used stand-alone (or with **Rush Hour II**).

Maybe some day in the future, when I have some time, I would think about implementing a new mod with something like this.

**Comment by Everybodyknows** [comment]
Yes you're right, my bad, the mod is not called "Real Social" 🙂
