### ISSUE TITLE
Use Math.Clamp() instead of custom RealTime.Tools.Math clamps?

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#145]
Just curious why RT uses custom clamps when there's [Math.Clamp()](https://docs.microsoft.com/en-us/dotnet/api/system.math.clamp?view=netcore-2.0)?

Another approach could be [this](https://stackoverflow.com/a/2683487/5240636) in a static class:

```
public static T Clamp<T>(this T val, T min, T max) where T : IComparable<T>
{
    if (val.CompareTo(min) < 0) return min;
    else if(val.CompareTo(max) > 0) return max;
    else return val;
}

Example: someNumber = someNumber.Clamp(min, max)
```

**Comment by dymanoid** [comment]
The `Math.Clamp` method you reference is only available in .NET Core. In _Cities: Skylines_, we're stuck in the Stone Age, however, and forced to use .NET Framework 3.5.

Using an extension method would normally be my approach, because it's neat and even avoids boxing despite of using interfaces. However, when performance matters, the code doesn't look so nice anymore. The clamp method must be called in the simulation loop (and multiple times). My custom method is 4x faster than the "nice" interface-based extension method you mention.

**Comment by aubergine10** [comment]
Nice!

For the `uint` clamp, would it be marginally faster if testing the `max` constraint first?

**Comment by dymanoid** [comment]
Why should it? The CPU branch predictor reorders the comparisons anyway.

**Comment by aubergine10** [comment]
Branch predication is something I need to learn more about - particularly what hinders it. Thanks for the infos!
