### ISSUE TITLE
Possibly an issue with citizen balance...

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#149]
Saw [this thread on Reddit](https://www.reddit.com/r/CitiesSkylines/comments/951v2j/having_a_real_problem_with_real_time/):

> My city pop is about 2200. My elementary school pop is almost 1100! I'm disabling RT for now and starting over. Anyone else have a problem with RT?

> I can't really grow a city like this. I had to build three schools in the first week and was on the verge of having to build another and my tax base couldn't handle it. Another problem was that in previous games I wouldn't fill a jail now I had to build a second police station just to handle the inmates. Juvenile delinquents maybe?

> I just started using this mod, it looks like when a new house is built, it starts with two parents and two kids. That’s why you have 1100 elementary students in a town of 2200, the other 1100 are thier parents. 
> 
> The really tough part is how long they take to age up and become educated workers, my entire town has been all level 1 buildings/services because everyone is still uneducated.

> With real time i get like 5 times as much ambulances driving around...

Could be related to #138 ?

I've personally noticed high number of school kids, but didn't perceive it to be a problem. I've not noticed an increase in ambulances when RT is active.

**Comment by dymanoid** [comment]
No issues with citizens balance, because **Real Time** doesn't change it. The only thing has changed is the citizens "aging" speed. Now a child needs 5 game days (20 "months") to graduate from an elementary school. A teen needs 10 game days to graduate from a high school. Students at university need 5 days too. So instead of building 100 schools, one needs to wait until citizens get educated. Once this first "wave" has reached the 3rd education level, the further development stabilizes.

One thing that makes it a little bit worse is that vanilla game spawns as new citizens mostly families of two adults (education random) and a couple of children (no education). No teens (high school eligible), no young adults (university eligible).

There are three solutions:

- don't rush and build your city wisely (no 100x schools, not too fast)
- use **Citizens Lifecycle Rebalance** mod to change the citizens aging and spawning behavior
- plop RICO buildings with citizens with required education and age already inside

**Comment by dymanoid** [comment]
#138 is not implemented yet, by the way.
