### ISSUE TITLE
Stuck public transport while boarding

### ISSUE THREAD

**Issue by dymanoid** [dymanoid/RealTime#170]
Some players reported that the public transport vehicles sometimes can stuck while boarding.
This occurs due to so-called "vehicle unbunching". There is also a hint that this issue occurs with **Rush Hour II** too.

I cannot reproduce the issue. Maybe this is caused by some other mod actually.
For the investigation, a save game is needed where the issue can be observed.

**Comment by aubergine10** [comment]
Only time I've ever seen anything like this happen was near a level crossing on which a train queue had formed due to me getting the junction settings wrong in TMPE.

If you ever fancy writing a mod that overhauls public transport, a replacement for IPT/TLM, I have a zillion ideas :)

**Comment by xavierwoo** [comment]
[stuckBoarding.crp.zip](https://github.com/dymanoid/RealTime/files/2997059/stuckBoarding.crp.zip)
Here is my saved game, you may see there is a train stuck at  metro line 7 (the white line).
Real time and citizen life rebalance are the only two mods enabled.
Hope this will help.

**Comment by xavierwoo** [comment]
I just remembered that I had used "Advanced vehicle options" to change the capacity of trains. After I re-set the value to default, the problem has gone. And I have to use the set default button in the mod, manually change the value to default doesn't solve the problem.

**Comment by dymanoid** [comment]
@xavierwoo, thanks for providing your save game.

I loaded it and observed the stuck train on the white metro line. However, eventually it started to move again without any change from my side. I inspected the game data, and the reason why this train waited for so long was a citizen who wanted to board that train but needed a little bit time to get to the train. 

So it seems that Real Time had no impact here. Other mentioned, that the vehicles got stuck forever, which is not the case here.

So I still cannot reproduce the issue...

**Comment by 1RedPanda** [comment]
It looks like the issue happens when windows (or the game?) starts to offload things from the RAM into the pagefile.
I noticed that after some time playing the RAM usage drops from 15,5GB (out of 16) to about 10-11GB, and at that point the issue starts (or so I feel).
Removing RealTime fixes it, so it has to be the mod causing this odd behaviour (maybe only when used together with IPT?) .

I hope this description might help solving the issue.

**Comment by dymanoid** [comment]
The issue is not being reported anymore on Steam. It looks like it was caused by another mods (in combination with Real Time).
Closing this one for now. If the problem still exists, the issue can be reopened.

**Comment by nsheaps** [comment]
I just had a reoccurrence of the issue but I just wanted to drop a line here for those having it again since I finally figured out what caused it, thanks to @xavierwoo's comment I'm not having the issue anymore after spending 3 days trying to fix it. 

As mentioned here and in other threads, it has _something_ to do with a conflict between Improved Public Transit (IPT2) and RealTime(RT). In my case I also had Advanced Vehicle Options (AVO) and Metro Overhaul (MO, amongst a bunch of others). 

I didn't try disabling as others did, but I did use AVO to set the speed of the m100  metro train included in MO from 125 km/h to 150 km/h. Doing so introduced a random time between when boarding was complete to when it actually moved on. 

I tried the following things:

* Disable unbunching completely
* Set unbunching to max 20
* Disable unbunching on the line
* Disable unbunching on the stops
* Set unbunching to 1
* Turn of/on citizens abandoning trips they're waiting for
* Disable a bunch of realtime settings related to dynamicism (like lights going off at night, and better traffic jam and transit waiting behavior)
* reset budget control

Ultimately what worked was using AVO to reset the m100 vehicle back to the defaults (of which I only changed the speed)


@dymanoid  would you mind sharing your steps for figuring out what is causing a train to wait before moving like you did [here](https://github.com/dymanoid/RealTime/issues/170#issuecomment-496724568) so the next time it happens we can do some investigation ourselves?

**Comment by aubergine10** [comment]
There's an issue which sometimes prevents cims getting on a bus/etc and the game then "floats/glides" them to the next stop on that line. The bus/etc waits until the floating cim(s) arrive at the next stop before continuing its journey. More details in this forum post: [Express Bus Services discussion topic](https://steamcommunity.com/workshop/filedetails/discussion/2262054175/3003299213532803308/) - see heading **"Bus just does not leave stop"/"Bus is sluggish to leave stop"**

So you could potentially solve the issue by using the [Express Bus Services](https://steamcommunity.com/workshop/filedetails/?id=2631360647) mod (and it's companion mods for IPT2/TLM integration, if applicable).
