### ISSUE TITLE
Does RT updarte sun position per frame?

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#188]
Constantly changing sun position causes shadow flickering, particularly on things like fences and power cables. I'm pretty sure RT does some degree of setting sun position; would it be possible to make sun pos update once per second rather than every frame? Could help reduce flickering effect?

**Comment by dymanoid** [comment]
Yes, **Real Time** updates the sun position each frame, exactly as the vanilla game does. When you disable **Real Time**, does the issue disappear?

**Comment by aubergine10** [comment]
It seems to stop, yes. I'll do some testing as I have a bunch of aesthetic mods which could also be causing issues.

I think the issue is that in the base game, the sun moves much faster - the shadows move in bigger increments. With RT, particularly on slow day speed, the sun is moving tiny amount each frame causing **Moiré effect** on shadows (particularly fence shadows).

A solution could be to limit sun position change to every X frames, where value of X is inversely proportional to daytime speed?

Note: The effect is not visible at night, it's only the bright daytime that causes it to be noticeable.

**Comment by dymanoid** [comment]
Are you using some additional post-processing mods?

On my graphic adapter, the shadows look even slightly better with **Real Time** because of slower sun movement, especially on speeds 1 to 3.

**Real Time:**
![realtime](https://user-images.githubusercontent.com/9433345/52534297-18dffc80-2d40-11e9-8680-8c2b8178f179.png)


**Vanilla:**
![vanilla](https://user-images.githubusercontent.com/9433345/52534285-f5b54d00-2d3f-11e9-934c-d56943ba9a67.png)

**Comment by aubergine10** [comment]
The flickering is far worse on my GT 640M 512KB than my GTX 1080Ti 11GB. Maybe it has something to do with vanilla graphics settings, which were obviously all set to minimum on the GT 640M.

**Comment by dymanoid** [comment]
@aubergine10, I think we can close this one, right? On a "low-end" graphics adapter and very low visual settings, there is always a chance the game looks strange.

**Comment by aubergine10** [comment]
yup
