### ISSUE TITLE
Garbage in Industry DLC buildings with the Lights out at night option

### ISSUE THREAD

**Issue by pcfantasy** [dymanoid/RealTime#196]
If enable turn off light in the night, the industry DLC building`s garbage will not count into the main industry building. So there will be a lot of garbage icon in player industry building

**Comment by dymanoid** [comment]
This issue is already known, the code causing this is the same as the one "fixed" in 5d621b486859401be7dd801575debae59ffc107e. However, the currently available industrial buildings seem to have enough capacity to store the garbage, so I didn't want to introduce even more patches because of CO's bugs in code.

Did you already observe the garbage problem icons for those buildings? With my test cities, there were no such icons because the buildings were able to store the garbage until the morning.

**Comment by pcfantasy** [comment]
@dymanoid 

Yes I can see garbage icon, maybe it is because I set night speed to 3x?
