### ISSUE TITLE
Abandon a ride when too long in congestion

### ISSUE THREAD

**Issue by dymanoid** [dymanoid/RealTime#2]
Cims should abandon the ride when they are too long in a traffic congestion. It doesn't make any sense to sit there all day long. This is especially useful when the vehicle despawn is deactivated (using another mods).

**Comment by aubergine10** [comment]
If implemented please make this feature optional.

An alternate approach could be to make the cim angry (much like cims get angry if they can't find parking in TM:PE, which in turn causes the destination building to become "more red" on the traffic info view).

Ultimately the player should be ensuring good transport options for their cims, and part of doing that requires knowing when problems arise - if cims silently abandon long trips, the player won't be aware of the problem and thus can't fix it.

**Comment by Sipke82** [comment]
It seems that the "Traffic Routes" info view is still available for color information :-)

**Comment by aubergine10** [comment]
Would this apply to PT? If not, could abandoning a ride set a flag to encourage the cim to try PT for that commute the following day? Like, the PT might appear to take longer based on what pathfinder says, but due to traffic jams it actually works out faster. I've often thought there needs to be some sort of gestalt switch that toggles cims over to PT if walking/cycling/driving isn't working out for them. And vice versa - if PT isn't working out, try walking/cycling/driving. It could potentially tie in with #57 .

**Comment by dymanoid** [comment]
This would apply to public transport too. If a citizen waits for a bus for, say, 1 hour (maybe configurable), he or she must say "f*ck that sh*t" and go find some entertainment around instead of heading to the target (work, shopping, event, etc.) If that's not possible, then he or she goes back home.

The question is, of course, how to make this problem visible to the player.

I think that the idea of choosing between car and public transport is good, but that will make **Real Time** incompatible with other mods that already mess around with citizens' path finding (TM:PE, Citizens Lifecycle Rebalance, etc.) I don't want to make **Real Time** incompatible with those mods.

**Comment by Sipke82** [comment]
> The question is, of course, how to make this problem visible to the player.

>  It seems that the "Traffic Routes" info view is still available for color information :-)

If buildings on that view turn red, then people have trouble reaching it.... (just like the ParkingAI of TMPE uses the Traffic view to show Parking availability)

**Comment by aubergine10** [comment]
> The question is, of course, how to make this problem visible to the player.

Yup.

Building colour change on Traffic Routes view is essential = where are problem destinations?

Chirps about commute woes would be really nice (how to prevent spamming though?) - while I don't generally keep chirp panel open, I do check it every so often to see what my cims are thinking. A chirp could include what the cim chose to do instead.

Can chirps link to a road, route or stop? That would help track down bottleneck. Otherwise I'd have to click cim name as soon as they chirp to get their current location at that time.

> I think the idea of choosing between car and public transport based on experience is really nice, but that will make Real Time incompatible with other mods that already mess around with citizens' path finding (TM:PE, Citizens Lifecycle Rebalance, etc.) I don't want to make Real Time incompatible with those mods.

I was chatting to Victor (TM:PE dev) and he mentioned that the choice (PT or not) is made prior to the path finder being invoked, i.e. it's external to TM:PE.

However, mods like citizen rebalance do change that stuff, but I think it's only when a cim first enters the city? Are those mods made by @DaEgi01 ?

Having a gestalt shift between transport preference is something the game is entirely lacking at present. There's two factors that could cause a shift:

1. Commute woes -- in scope of RT, but also TM:PE, TLM, IPT...
2. Cim state (age/wealth/etc) -- Outside scope of RT, probably belongs in a rebalance mod?

From memory, IPT an TLM track "time until bored" at PT stops. I assume it's used to set desirability of a route or something? I suspect vanilla game also tracks that metric but don't know how to check.

**Comment by dymanoid** [comment]
I guess, players won't get it right when a whole industry district will become red in the traffic view. Almost everyone knows, that this means 'no free parking places' - TM:PE is very popular. Is this ambiguity a right thing to do? I'm not sure.

**Comment by DaEgi01** [comment]
@aubergine10 no, i am not the author of https://steamcommunity.com/sharedfiles/filedetails/?id=654707599 but WhitefangGreytail, see https://github.com/WhitefangGreytail/WG_CitizenEdit

**Comment by Sipke82** [comment]
@Dymanoid, indeed don't touch the "traffic" info view, it is used for parking AI of TMPE (when that gets fixed =)

But the "Traffic Routes" infoview is still empty and could be used? ( https://i.snag.gy/EczjBo.jpg )

**Comment by Everybodyknows** [comment]
Hi, 
Maybe citizen, should abandon ride only if it's for leisure activity. In case of work, citizen should work longer to catch up the delay. 
Regards.

**Comment by dymanoid** [comment]
@Everybodyknows, what if the citizen spend all day in a congestion and arrives at work when their shift is already done and the next shift workers are arriving?

I think that the citizens should abandon their rides towards workplace too. It's also somewhat realistic. If you're stuck in a traffic jam for 3 hours, you will probably call you boss: "Hey boss, I cannot reach my office today, sorry. Can I take one day off work today?"

**Comment by Everybodyknows** [comment]
@dymanoid Yes you're entirely right. In that case, (say, more than 2 hours of travel, I think 4 hours is too much, but maybe it's a detail for now), the citizen should abandon the journey. 
But in case of many abandonment, the citizen should resign and search a new job at approximatively one and half hour max from his home (for example). Is it possible to implement that? this will have a interesting impact on the way to plan the areas.

For now with this feature planned, what is the impact of the travel abandon? The productivity and therefore the incomes?

**Comment by aubergine10** [comment]
I assume the timings will factor in speed slider settings?

Traffic and pedestrians move at fixed rates regardless of those sliders, but time doesn't. So in slider speed = 1 (almost real time) the 'late time' would be longer than it would in slider speed = 6?

**Comment by aubergine10** [comment]
> @Everybodyknows : But in case of many abandonment, the citizen should resign and search a new job

I assume abandoning trips will result in fewer workers/customers which in turn would impact the economics of the building?

**Comment by Everybodyknows** [comment]
> I assume the timings will factor in speed slider settings?
> 
> Traffic and pedestrians move at fixed rates regardless of those sliders, but time doesn't. So in slider speed = 1 (almost real time) the 'late time' would be longer than it would in slider speed = 6?

We touch a sensitive point of the mod there. In that case I see four way :
- Find a way to link the speed simulation with the speed of traffic and pedestrians move.
- Set a speed simulation without options speed and match the two speed
- Find the best setting of speeds simulation (who match with the two setting), and advise the most efficient setting for the users. 
- Yours, workaround (not bad, certainly the easiest way, but it's not my preference) with set the "late time" according to the speed setting simulation.   

> I assume abandoning trips will result in fewer workers/customers which in turn would impact the economics of the building?

Yes, the best thing would be that it happens. But is it possible to implement? I don't know, I'm not programmer :D
