### ISSUE TITLE
Error when city loads in (real time mod not working)

### ISSUE THREAD

**Issue by shaneturner12** [dymanoid/RealTime#203]
When the city loads in, an error appears that Real Time failed to load properly and to report the issue. There is also mention of patching errors in the output file.
[output_log.txt](https://github.com/dymanoid/RealTime/files/2960563/output_log.txt)

**Comment by dymanoid** [comment]
This issue seems to be caused by the mod "[Smart Intersection Builder](https://steamcommunity.com/sharedfiles/filedetails/?id=1677913611)". It uses the Harmony library version 2.0.0 which has some new bugs and introduces breaking changes in its API (new `ArgumentNullException`s).

You can unsubscribe from that mod to get Real Time running. Also take a look on that mod's description.
