### ISSUE TITLE
Make citizens go to the nearest shelter immediately when an evacuation starts.

### ISSUE THREAD

**Issue by melvin2204** [dymanoid/RealTime#206]
Could you add something to make citizens go directly to the nearest shelter when the alarm goes off? Another nice thing to have would be to make them go on foot instead of the car and creating gigantic traffic jams.

What currently happens: when an alarm goes off, citizens at work/school will go home instead of the shelter. People already at home will directly go to the shelter. Also, when they go to the shelter, they choose a random shelter and travel there. This also generates traffic jams because many citizens try to go from one side of the city, to the other.

What should happen: as soon as the building gets evacuated, citizens should go to the nearest shelter immediately. When in walking distance: go by foot, or else: go by car or to the nearest evacuation bus stop.

Thanks.

**Comment by dymanoid** [comment]
On evacuation, the game decides which shelter each citizen chooses. There is already a comprehensive logic, and the game tries to choose the nearest shelter for each citizen. If a citizen goes to a "random" shelter, then obviously all the places in the nearest shelter were already "reserved" for other citizens.

Furthermore, Real Time will never change the way **how** citizens get to their destinations (by foot, by car, by public transport, by bicycle). Real Time only decides **when** and **where** to go. So this should be a part of another mod indeed. Maybe I could create a "Real Evacuation" mod or something, but have no plans currently.

As soon as a single building is evacuated, the citizen tries to find another activity or simply goes home. If there is a global evacuation, all citizens try to find a shelter. If this doesn't work for you, we need to investigate deeper.

And the last point - there is no way to get all citizens moving "immediately". The game processes the simulation in chunks, so e.g. when a particular citizen wants to evacuate, they may actually start moving e.g. only after 40 in-game minutes because that citizen happens to sit in the last "simulation chunk". That is how the game works, and this cannot be changed. The game needs a way to simulate up to 1 Mio citizens without burning out your CPU.
