### ISSUE TITLE
Compatibility mode for Realistic Walking Speed

### ISSUE THREAD

**Issue by dymanoid** [dymanoid/RealTime#218]
In #133, a better travel time estimation was implemented.

However, activating the mod **Realistic Walking Speed** invalidates those empirical evaluations.

There should be a special compatibility mode in **Real Time** when **Realistic Walking Speed** is active. In this mode, the travel time estimation values need to be changed. They will of course differ from the vanilla game, because the citizens move much slower on foot.

**Comment by DaEgi01** [comment]
public const float AverageDistancePerSimulationCycle = 600f;
i see. you can't calculate that based on actual speed can you?
i have not idea how the actual process for cims is. but i guess they just pick to walk/car/whatever and directly execute it.

**Comment by dymanoid** [comment]
There is no chance to calculate the actual speed for every citizen instance (without burning out the CPU).
Furthermore, **Real Time** needs that average speed *before* the trip starts. At that time, the path from source to target was not calculated yet, so it's just unknown how (fast) the citizen will move.

The empirically obtained value `AverageDistancePerSimulationCycle` is just an overall average speed measured with a large city over 24h. It combines all travel possibilities (on foot, bicycle, car, public transport). It is way too imprecise, but it's better than no value at all.

I will just need to perform another measurement with **Realistic Walking Speed** active to get a new empirical value for this case.

**Comment by DaEgi01** [comment]
i see .. so you have to make the decision and all you know is where you are and what your target is.
neither the mode of movement, nor the actual path. i guess the empirical value is the best way to handle it. the only thing you could do is maybe a self adjusting value instead of a constant. so if cim reaches target much too late, decrease by a small amount, or increase if cim is much too early.

**Comment by DaEgi01** [comment]
MaxWalkingDistance in TM:PE does also affect the value :/

**Comment by dymanoid** [comment]
Self-adjusting won't help, because there will always be citizens that arrive too late or too early. The path finding is affected both by the current traffic situation and by other mods.

I think the most pragmatic way is to use some approximated value. It just need to be different when the **Realistic Walking Speed** mod is on.

**Comment by DaEgi01** [comment]
i think self-adjusting does indeed help.
i never said it made it perfect, only that it improves the situation somewhat but cost some cpu cycles.

what I had in mind is:
you start with the value that is a constant right now, lets say 600.
a cim calculates when to leave the house to get to work on time, lets say work starts at 08:00am.
on arrival the cim checks, if it reached the target inside an interval around 08:00am +- x hours for example 3h.
if cim arrived after 12am you decrease 600 by 0.001% (should not get negative).
if cim arrived before 5am you increase 600 by 0.001flat (should not rise too fast).
so .. lots of cims arriving at work much too late due to the traffic situation that got worse, they will leave the house a little earlier the next day.
if it gets better again, cims will leave the house a little later.

or is the a fundamental error in my reasoning?
i know that there will always be outliers and that is ok. the increase and decrease values should be tuned, also the time interval which leaves the value untouched. i just think that a fixed value won't do it due to the dynamic nature of the problem. 
if you tuned your value for 80% traffic flow, it won't work for 60%.
ppl in reallife would adjust. cims with a constant value never adjust.

**Comment by dymanoid** [comment]
The "home -> work" route is already being monitored for each citizen in **Real Time**. The mod tailors the departure time for each citizen according to their last few trips to work. This already works pretty well, because the route is *relatively* stable and the workplace will not change that often.

However, we cannot do this for any random destination. There are just too many factors affecting each trip.
