### ISSUE TITLE
Education takes too long since the Campus DLC update

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#220]
FYI: https://steamcommunity.com/app/255710/discussions/0/1640912759107682620/

User wrote:

> ### Any mods to revert education system to the way it was?
>  
> The new education system overhauled in the Campus DLC doesn't work very well with Real Time, imo. Citizens move into the city as adults, and promptly are uneducated and cannot climb the education chain, but because time moves so slowly, it takes FOREVER for them to have children and die off so that the population starts becoming educated.
>  
> I set the time-of-day speed set to max on the highest simulation speed and left for the movies yesterday to let the game play by itself and my population hardly changed when I came back. Residential takes forever to level up and commercial is constantly being abandoned because there are not enough educated workers. 
>  
> I unticked the option in Real Time for the more realistic Cim aging to see if it would help and what happened instead was the population exploded as my meager city of 5000 were having 91 babies every 20 minutes. I don't even know where they were putting all those people, the city tripled in size without me zoning anything.

I assume the issue is that now cims must go through specific sequence, and in specific building types, to get educated. Before a child could be in a university to get their elementary education, etc., whereas now they can only get a certain level of education a) after gaining previous level and b) they need to attend correct type of building.

**Comment by AngryScandinavian** [comment]
Hey that was me! https://github.com/dymanoid/RealTime/issues/219
I am not github savvy and I like the way your post is formatted/phrased far better than mine. 
Further in that discussions thread I was more explicit in what was occurring so I will also quote that here:

> In both the new and old education systems, you are required to be educated before you are well educated, and well educated before highly educated. Each corresponding with a different tier of schooling.
> 
> However, in the new system, the age brackets are now connected with a type of school. Adults cannot go to elementary school, and because thats a preliminary for being well and highly educated, they are permanently uneducated (except for random chance.)
> 
> Allow me to re emphasize - THIS IS A GOOD THING FOR THE BASE GAME. Under normal circumstances a Cim may not go to elementary school and you will then have an uneducated worker for some basic labor jobs until they die.
> 
> My ONLY problem is the way this interacts with the Real Time mod. All of those initial uneducated adult Cims that moved in are permanently uneducated until they die (which takes longer in this mod) and/or give birth to someone who can climb the education chain because they will be of the proper age to attend elementary school.
> 
> In the old education system, the Cims that moved in would still last a ridiculously long time, but while they were alive they could participate in the education system. 
> 
> I waited six whole hours of being completely AFK and there was hardly a dent in the populations education. It could be a dozen more before the cycle starts up correctly and at that point the mod is hampering the experience by requiring you to wait essentially 20 hours before some parts of the game even occur. 

If I could get an approximation for the lifespan of one Cim in "Real Time" in game days I could rule out whether or not this is a bug as I would know when the population should have shuffled through. 
As it stands now I have idled in my game for way too many hours for the system to be enjoyable.

**Comment by AngryScandinavian** [comment]
Here are a few other instances of users referencing this conflict of systems
![image](https://user-images.githubusercontent.com/38747359/58606159-35506800-824f-11e9-9523-7b6fff518485.png)
![image](https://user-images.githubusercontent.com/38747359/58606177-48633800-824f-11e9-832d-5f721acc48b9.png)
![image](https://user-images.githubusercontent.com/38747359/58606222-7779a980-824f-11e9-84ff-af35efdb592a.png)

**Comment by aubergine10** [comment]
Ah, sorry, didn't see the issue you created (Google Chrome doesn't seem to like updating the issue list without a page reload ugh).

**Comment by dymanoid** [comment]
Thanks for the feedback.

This isn't an issue in **Real Time**. This change of the education system was already known, but I didn't change how **Real Time** works.

I think, the root cause of the issue is the fact that the vanilla game sends mostly uneducated adults with uneducated children as new citizens, no young adults at all and no educated citizens. To mitigate this, you could use the **Citizens Lifecycle Rebalance** mod or deactivate the **Better aging and birth rate** option in **Real Time**.

However, if you still want to use that option of **Real Time** but don't want to use the other mod I mentioned above, you run into troubles described above.

I think, I will change the new citizens distribution (age and education), similar to the other mod. **Real Time** will then send more educated adults and young adults (and maybe even seniors) with all education levels. This functionality will be active when the **Better aging** option is on and the **Citizens Lifecycle Rebalance** mod does not run.

**Comment by AngryScandinavian** [comment]
> I think, I will change the new citizens distribution (age and education), similar to the other mod. Real Time will then send more educated adults and young adults (and maybe even seniors) with all education levels. This functionality will be active when the Better aging option is on and the Citizens Lifecycle Rebalance mod does not run.

This feels like the best course of action. **Citizen Lifecycle Rebalance** is a great mod, but it doesnt have any options for turning parts of it off. The illness and mode-of-travel scale could be tolerable but its own aging scale still does not suit **Real Time** as well as its own **Better aging** setting does (as seen below) and that aging scale takes priority over Real Times so you are forced to use it even if you just want random initial Cims.

- **7000 Population**
- 1 birth / 20 min Real Time Better Aging
- 90 birth / 20 min Real Time no Better Aging
- 43 birth / 20 min Real time with Citizen Lifecycle Rebalance installed

I think it could still be important to list somewhere on the workshop page how long a Cims lifespan should be expected to be with the **Better Aging** option turned on, so we know when to expect the whole population to start being educated. To my understanding a normal Cim lives 6 years, and this mod has 1 day equal to 1 year, but there must have been some other life scale change because obviously the time to educate well passes 6 days. 

At any rate, I still believe a mod reverting the education system back would be the most optimal solution, as even with better age and education distribution on new citizens some will still be education-deadlocked for an incredibly long time. I appreciate your work and your response nonetheless.

**Comment by dymanoid** [comment]
@AngryScandinavian, a "normal" Cim lives up to 85 years (as you would normally expect from a human being - but don't ask why the game developers have set 85 years as 100% death age), that means up to 85 days in **Real Time**, independently of the time speed. Where did you get that number of 6 days from?
