### ISSUE TITLE
Stop garbage accumulation at night

### ISSUE THREAD

**Issue by funbaker** [dymanoid/RealTime#228]
This would allow to shut down garbage collecting buildings to be shut down at night as well.

**Comment by dymanoid** [comment]
Thanks for suggestion. What is the benefit of this feature? Does it solve some problem or does it improve the game experience somehow?

**Comment by funbaker** [comment]
More realism. At the moment there are garbage trucks going all night. Reducing the budget results in garbage overflow (Well, maybe not completely stop garbage, theres has to be the right balance).

**Comment by aubergine10** [comment]
Instead of turning it off at night, could it be configured to collect from different building categories depending on shift?

|Shift       | R    | I     | C    | O   | X |
|---          |:---: |:---: |:---: |:---: |:---: |
|Morning | ❌ | ❌ | ❌ | 👍 | 👍 |
|Day         | 👍 | 👍 | 👍 | ❌ | ❌ |
|Evening  | ❌ | ❌ | ❌ | 👍 | 👍 |
|Night      | ❌ | 👍 | 👍 | ❌ | ❌ |

Where "X" = other stuff, such as parks, monuments, stations, services, etc., although those things could have shift-dependent profiles too? For example, parks most active in day, so treat like office?

This way cims get a good night's sleep.

There could be profile for weekdays vs. weekends (e.g. commerce more busy during day at weekend so might not want garbage trucks buzzing around).

**NIMBY** policy districts could prevent garbage collection at night? Same for **Old Town** and **Heavy Traffic Ban** policies?

**Comment by dymanoid** [comment]
From the technical point of view, changing the garbage collection behavior is not that easy. There are other mods too, that affect this behavior. So the only feasible solution would be to disable garbage accumulation for all buildings at night. But this will impact the economy and other infrastructure too (electricity etc).
I decide to not implement this feature in scope of Real Time.
