### ISSUE TITLE
Synchronize the temperature with the daytime

### ISSUE THREAD

**Issue by dymanoid** [dymanoid/RealTime#23]
Currently, the temperature changes too fast when **Real Time** is activated. This has to be fixed - the temperature change speed must be significant slower that in the vanilla game.

**Comment by aubergine10** [comment]
Would this be better in a separate Seasons mod? It would be applicable for vanilla games also.

I'd ideally like to see temperature and weather linked. For example, on a clear night the temperature would drop much more quickly than on a cloudy night. I'd like to see fog and mist linked to season and temperature, and so on.

I'd also like non-Snowfall maps to be able to experience sub-zero temperatures (I've never seen a boreal map go sub-zero, maybe I just didn't notice?) - visualisation could potentially be achieved via integration with (or merging code from) Relight and Ultimate Eyecandy mods.

Over time, other effects could be added - for example, cold frosty weather could increase the chances of various types of lunar and solar [halos](https://www.wikiwand.com/en/Halo_(optical_phenomenon)), potentially visualised via the same technique vanilla game uses to add [aurora](https://www.wikiwand.com/en/Aurora).

**Comment by aubergine10** [comment]
As mentioned on Steam, sunlight intensity also needs adapting to RT - currently it seems hard coded based on time of day, rather than position of sun. Sunlight intensity can also feed in to weather patterns - for example it determines the rate of temperature rise/fall, amount of evapotranspiration and so on.

**Comment by DaEgi01** [comment]
there is a mod for that already ... why not make it compatible?

**Comment by dymanoid** [comment]
I'm not planning to create a fully customizable seasons/weather mod. This feature only addresses the issue that the temperature currently changes too quickly (unrealistic).

**Comment by aubergine10** [comment]
That's a shame, but understandable.

If possible, could you check in to the "sunlight intensity" thing though? As far as I can tell CO hard-coded it to be certain times, rather than sun position (or even the game's own notion of daytime vs. night time).

Ideally it should be 0 between sunset and sunrise, because no sun, and 100 only when sun is at highest point in sky (rather than 'noon').

This is particularly important when the dynamic sun position thing is enabled, as 'daytime' hours (and sun max position) will change time throughout the year.

**Comment by dymanoid** [comment]
> As far as I can tell CO hard-coded it to be certain times, rather than sun position (or even the game's own notion of daytime vs. night time).

No, the sun intensity is not hard-coded. The current formula is:

    daytime_intensity = 0.5 + min(current_hour - SUNRISE_HOUR, SUNSET_HOUR - current_hour) * 2
    daytime_intensity = fit_in_range(0.0, 1.0)
    sun_intensity = daytime_intensity * (1 - max(current_rain, current_fog) * 0.5)

**Comment by aubergine10** [comment]
So it's based on time, not sun position.

Assuming the all-caps values are constants that don't change while playing, that would explain why I was seeing solar panels working after sunset in winter.

Could it reuse result of whatever calcs are being used to depict the sun position on that circle in the bottom-left corner of the screen?

**Comment by dymanoid** [comment]
All-caps are not constant in **Real Time** environment; otherwise, of course, are. But anyway, this is off topic for this issue. It only addresses the temperature change speed.
