### ISSUE TITLE
Restrict maximum active construction sites

### ISSUE THREAD

**Issue by dymanoid** [dymanoid/RealTime#26]
Currently, the construction sites are all active at the same time. So it doesn't look realistic when the half of the city is upgrading/constructing. The maximum of active construction sites should be restricted.
This should be a configurable parameter.
For upgrading, this might cause issues: when many buildings want to upgrade at the same time, what happens with the "paused" ones? To investigate whether the upgrading triggers can be delayed or whether the paused upgrades affect anything.

**Comment by Sipke82** [comment]
Perhaps the maximum bumber of construnction sites should be depended on city size? As larger cities would have more construction companies :-)

**Comment by Owlchemist** [comment]
This could be useful for balance reasons too. I'm not 100% sure on this, but from what I've noticed, the RCI only responds to finished construction. So if there's a tiny bit of demand and you have construction set to slow, you might get far too many construction projects responding to it. It's not a problem in vanilla since the buildings are raised so quickly.
