### ISSUE TITLE
Interconnection with external cities

### ISSUE THREAD

**Issue by scwall** [dymanoid/RealTime#268]
Hi, I've been playing this game lately and I think it's fabulous and your mod makes it even more realistic. One thing that would be great is to be able to have a connection with external cities (a bit like the last sim city). I suspect that not everything is possible, I was thinking for example: people can also work outside the city or do their shopping, buy electricity or water in nearby cities, neighboring cities that come to our city to work or do their shopping. See you soon :)

**Comment by Dushess** [comment]
I like your idea, this need an emulation of destination point for a cim. It also means storing all his data and continue calculations, after despawning all described things gonna be counted (also random time splits, since we can't said precisely where he works and how far from our cityis all of those areas). Then same transport with same cim should be spawned as entering city again. Hope it is possible here.

**Comment by dymanoid** [comment]
This is an idea for a new mod, actually.
Check out this one: CitiesSkylinesMods/CitiesSkylinesModWishList/issues/8
I will not implement it directly in Real Time, because that would make the mod too complicated.
