### ISSUE TITLE
Configurable work shifts

### ISSUE THREAD

**Issue by dymanoid** [dymanoid/RealTime#29]
The second shift and the night shift should be configurable - how many citizens work second and night shift. As of version 1.1, the distribution is hard-coded to 25% for each.
This can lead to way too heavy night traffic in large cities with lots of 24h-available workplaces.

**Comment by aubergine10** [comment]
When I first installed RT, I was seeing obvious rush hour even on 7k pop city. Since 1.0, I  no longer see that because of extra shifts. My city is currently at 15k and it's only just showing initial tiny signs of rush hour.

While configurable rations would mitigate the issue, I propose a concept of 'work shift milestones' as an alternative:

```
Shifts:              A              B                C              D
Population: ---|---------|----------|---------|------>
```

Initially, no workshifts - vanilla functionality. Player is just starting out and focussed on other stuff like water, energy, etc. Also, population is too low for any effects to be noticeable.

When city reaches ["Worthy Village" milestone](https://skylines.paradoxwikis.com/Milestones), the initial shift (daytime) kicks in. This is a special shift, because most (all?) cims transfer to it immediately. While pop is still too low for rush hour to be seen, the player should at least be able to discern the work/leisure pattern.

City grows until there is noticeable rush hour - likely around "Busy Town" milestone - and player has to change their transport infrastructure to accommodate it.

Note: All times below just for illustration.

When player reaches "Big Town", the next shift becomes available (early-morning shift? I'll call it "morning" shift for brevity) - but only a small number (percentage) of cims are initially allocated - we don't want the daytime shift rush hour to suddenly disappear (although it might shrink a little, as some cims initially migrate over to the new shift).

As the city continues to grow, the percentage assigned to second shift increases until it has it's own associated rush hour (likely around "Big City" milestone). The daytime shift continues to grow as well, but at much slower rate due to the morning shift soaking up the excess cims.

As city continues to grow, the evening and eventually night shifts also become available. Ultimately, player ends up with 4 shifts delinated by rush hours. Note also that the shifts would interact. For example the morning shift reduces growth rate of day shift, but people leaving with morning shift clash with people starting day shift (so the growth of morning shift actually makes the daytime rush hour worse, in addition to gestating it's own early morning rush hour).

This will add much needed "oh shit" panic moments to the game - just as player is solving the daytime rush hours (say 9am and 5pm) the morning shift starts exacerbating the 9am rush hour (cims going home at end of morning shift clash with cims going to start day shift), and just as player gets that resolved, the rush hour associated start of morning shift emerges (4am?) and they have to deal with that. Then the evening shift kicks in, making 5pm rush hour worse, and eventually adding another rush hour at 11pm. Then the night shift kicks in, making both the 11pm and 4am rush hours worse at the same time.

There could also be flexitime effect kicking in, one shift at a time (eg. when evening shift becomes available, the dayshift could gain flexitime; when night shift becomes available, the morning shift gains flexitime; and, as city continues to grow, virtual milestones - which only change existing shifts - would add flexitime to evening and eventually night shifts).

Alongside all this, you've got cims participating in leisure and shopping - which are affected by the shifts and flexitime too. And then on top of all that, there's the school start/stop rushes which are somewhat disconnected from the work shifts.

If a city shrinks (because deathwave or natural disaster, etc), the work shifts could essentially "de-milestone". This could cause a flexitime or even entire work shift to be removed.

So what starts out as a simple concept of rush hour turns in to multiple rush hours, that start colliding, then elongating, etc.

Open hours of leisure and shopping could be affected by the work shifts and flexitime too. Initially, for daytime shift, shopping happens in morning (on way to work), lunch, evening and weekends. As morning shift kicks in, shops now have a few extra surges to deal with. Then evening shift kicks in, so shops have even more surges of customers. So shops and leisure open hours would increase until eventually they're 24/7.

**Comment by dymanoid** [comment]
Thanks for your thoughts. But I thing this is way over-complicated. You'd need some means to tell the player what's going on and when; otherwise, they will drop the mod because of not being able to solve constantly emerging rush hours. Further more, the game doesn't provide any possibilities to control the citizens' work behavior so precisely. To solve that, we'd need a second game simulation running in background. That would cause performance problems and would need lots of additional RAM, not to mention restricted space in the save game for custom data.

For the next release, I will implement two sliders for the second and the night shifts. The player can configure them, but only statically. Of course, they still can be changed during the game, but they won't be changed automatically.
