### ISSUE TITLE
Bug? Commercial demand drops to zero at nights

### ISSUE THREAD

**Issue by Sipke82** [dymanoid/RealTime#38]
At daytime my commercial demand is high, but at nights it drops to 0

**Comment by dymanoid** [comment]
The demand depends on many factors. **Real Time** doesn't affect the demand directly, but rather indirectly. But from my point of view it's OK when there's no commercial demand at night. Most citizens are sleeping at night - why there has to be great shopping demand then?

**Comment by Sipke82** [comment]
While i agree that it is logic that there is no demand for actual shopping, in my perspective the RCI meters are more of an "overall" reflection the city needs. And those needs shouldn't change just because most of the cims are sleeping. They will still want shopping the moment they wake up.

**Comment by dymanoid** [comment]
This would need a massive intervention into the game's demand logic, because it seems that the vanilla demand depends primarily on the customers count. I didn't plan to change anything in the demand logic, because there are mods that do this already. I don't want to include in **Real Time** these features that are already available in other mods (like e.g. parking AI, demand optimization etc.)
