### ISSUE TITLE
Day/night speed depended on time instead of sun dawn/set

### ISSUE THREAD

**Issue by Sipke82** [dymanoid/RealTime#41]
Could you make it an option to trigger day and night time on a specific time? because on some maps the rush hour now takes place in night time.

**Comment by dymanoid** [comment]
To shift the rush hour, use working hour sliders. Rather than specifying an exact time for a speed switch, it is better to go the #31 way. This needs to be thought out well, however.

**Comment by Sipke82** [comment]
Well i don't want to change the rush hour time......

I want to make sure that the faster Night time, starts at for example 11 PM, instead of the start at sunset.

I Believe #31 is to add additional slowdown.

**Comment by dymanoid** [comment]
With the 'slow down on rush hour' option activated, the time will flow slowly even after sunset (supposing a faster night time speed is set), until the rush hour ends. So #31 solves your problem in a nice way, I think.

**Comment by dymanoid** [comment]
Okay, I reopened this issue. You say we need some kind of "business hours", as mentioned in #34 and #31. What about weekends? "Business hours" on Sunday? No, we need another name. But the idea makes sense maybe.

**Comment by Sipke82** [comment]
Why not "Realtime" and  "slow time"?   it fits the mod :=)

**Comment by aubergine10** [comment]
_Note: The title of this issue should perhaps be changed: "Duration of working day should be independent from sunrise/sunset"_

While the speed setting is a factor in this, it also encompasses budgets and affects the general patterns by which a city operates.

> Spike82: Why not "Realtime" and "slow time"? it fits the mod :=)

No, anything with 'time' will just confuse things more. There are already too many types of time lol.

> dymanoid: "Business hours" on Sunday? No, we need another name.

At weekend, there is still a sort of 'business day' for the people working in shops...

Actually, the [concept of "Shopping Hours"](https://www.wikiwand.com/en/Shopping_hours) is ideal - those hours encompass the active period both on weekdays and weekends, at least in people's minds (for example, the term "late night shopping" illustrates that even though many shops might be open longer than normal, or even 24/7, the public still perceive a certain window of time which they call "shopping hours", and most transit happens during in those hours).

Whatever we end up calling it, ideally there should be sliders to set the window for each of the 7 days.

_I urge the use of the vanilla day/night sliders (as seen on budget panels) as it will help people see the link between these settings and the day/night aspect of budgets._

Why have setting for each individual day? Because...

During the 'business days' (Mon-Fri) many places have a half day. Where I live, rural England, it's Wednesday - many of the businesses, particularly low density commerce and industry, shut at 2pm. In rural Scotland it's generally 11am or 12pm when they shut, either on a Tuesday, Wednesday or Thursday. In Islamic countries shops often close on Fridays, and so on.

Saturdays and Sundays have distinct patterns pretty much everywhere. For example, in many countries people are far more active on Saturdays (shopping, partying and other recreation) than any other day of the week. Whereas people are more chilled on Sundays because they've got work the next day.

All these patterns largely coincide with "shopping hours".

**Comment by aubergine10** [comment]
Addendum: An option, per day of week, to specify whether some shops remain open outside of shopping hours would be useful.

For example, some places have bans on Sunday shopping - so there would be no shopping hours on Sunday, but also no shops operating outside those hours. On other days, some shops will remain open outside shopping hours. But it's not unique to Sundays; for example Islamic countries often have complete shopping shutdown on Fridays and so on.... so a checkbox next to each slider to define if shops are allowed to open outside those hours.

**Comment by Sipke82** [comment]
Personal i think that day and night time are not that bad names.. and they correspond nicely with the budget sliders in the game. IMO players will understand the difference between day and night time. and that is is possible that the sun is already set at day time.

Although i like the ideas of aubergine of per day sliders, I'm not sure if that would be over-complicating matters. perhaps we can settle for discrimination of weekdays and weekends.

IMO opening of shops and stuff should be related to the work shifts and not be related to day/night time.

**Comment by dymanoid** [comment]
We should not forget that it's just a game and not a real city simulator. Over-complicating things is not the good way IMHO. Statistically, the more options and settings users get available, the less those options will be ever changed. This is proven.

Here is my idea how we can start:

- we introduce two user-configurable parameters: _"wake up time"_ and _"go to sleep time"_
- these apply every day regardless of day of week
- these are decoupled from sunrise and sunset
- time between _"wake up"_ and _"go to sleep"_ is considered as _day_ (both by citizens and by game's budgets)
- time outside of that period is _night_

Once this is implemented, we can listen to players' feedback and maybe enhance some points, if necessary.
