### ISSUE TITLE
Changing construction speed mid build = pancake buildings

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#47]
I had construction speed set to 1, placed a few new buildings to be constructed. Got bored waiting and ramped construction speed up to 100. The buildings were then pretty much instantly constructed, however they were flat like pancakes. Changes to roads or doing any bulldozing in the area seemed to "inflate" them back to normal shape and size.

**Comment by dymanoid** [comment]
This is somewhat caused by the game itself. It just cannot handle those massive construction speed changes, because actually it doesn't even support dynamic construction speed. To fix this, a great effort is required, while the benefits/outcome of such a fix is rather negligible. I will post it as a "known issue", but won't do anything about it.

**Comment by aubergine10** [comment]
Is there some way to detect when a construction completes and maybe check to see if the building is pancaked and if so inflate it to normal size?
