### ISSUE TITLE
More precise citizens behavior simulation

### ISSUE THREAD

**Issue by dymanoid** [dymanoid/RealTime#57]
Current citizens behavior simulation is based on the state that is provided by the vanilla game.
By introducing custom state structures, the simulation can be made more precise and realistic.
Features:

- citizens remember how much time they need to get to work (in average) and start moving to work according to that
- this should of course react on game changes (new transport networks, new roads, etc.)
- more exact state tracking (lunch, relaxing, shopping, etc.)

The persistence has to be well thought thorough, because the game provides limited space for custom data.

**Comment by aubergine10** [comment]
Citizens generally follow same routine each day, which has me pondering...

Could the path, once calculated, from home to work, and from work to home, be remembered for each citizen? And same sort of thing for students going to/from school.

This could save a huge amount of pathfinder work, at the expense of some RAM and locating a record in a lookup table (likely still less time than engaging the pathfinder).

When time comes to go to work, for example, it's a quick check (same technique a bus would use to work out if it can reach the next stop) to see if existing path is still valid and if so use it (otherwise calculate fresh path).

Obviously we want some variance, so some chance the routine changes - "I'm nipping to the shops on way home from work today". In this case one-off path would be calculated as usual and not stored, but then the next day it's back to normal routine so use the stored path.

While a path might remain valid for a long time, improved transit routes should be used when they become available - so stored paths should have a TTL after which they expire.

Paths wouldn't be stored in the save game, as there's a limit (16MB I think?) on amount of data mod can store in a save (as noted in one of the open, or recently closed, TM:PE issue tickets).

Re-using stored path could be applied to a percentage of cims to help with bulk processing (branch predication, etc). So if 90% are told to get to work on time, that batch would be using the stored paths, the rest would be getting new paths with some occasional shopping and days off.

From vague memory, pathfinding is one of the main limiting factors on how many cims the game can handle. The notion of a daily routine could offer a partial improvement in that respect?

**Comment by dymanoid** [comment]
Path finding is indeed out of scope for **Real Time**. There are lots of mods that do this already, and I don't want to introduce yet another path finding. Neither want I make **Real Time** incompatible with all those traffic management mods (IPT2, TM:PE, etc.) Finally, I doubt that a path can be cached at all. Checking whether a path is valid means performing path finding again, actually. So no merit.

**Comment by dymanoid** [comment]
> Isn't pathfinding is one of the main limiting factors on how many cims the game can handle? The notion of a daily routine could offer a partial improvement in that respect?
No. These are hard coded values. Max count of "real" visible citizens (incl. driving cars, bicycles etc) is 65.525. Max citizens count in the city is 1.048.575.

**Comment by aubergine10** [comment]
Cims having daily schedule is freaking awesome!
