### ISSUE TITLE
Correct "per week" stats

### ISSUE THREAD

**Issue by Sipke82** [dymanoid/RealTime#59]
In the PT lines overview, you have for example 3000 cims per week, but that is in the simulation time and in the real time. I guess it's more like 3000 per hour?

So either replacement of the word "week" to "hour" could work, or show the actual week stat, so i guess more like, 50000 per week.

This also applies for parks and unique buildings, and other stuff i forgot.

**Comment by dymanoid** [comment]
Following statistics need to be updated:

**Main tool selection panel**

- transport overview (passengers)
- citizens overview (births/deaths)
- natural resources
- tourism
- tours overview (attendees)


**Tool panels**

- transport line overview
- tour overview
- budget (tool tips)
- city info (tourists)
- credits


**Main panel**

- new building tool tips (upkeep and water)
- money/citizens tooltip


**Info panels**

- water & drain (productivity)
- garbage processing (productivity)
- power plants (coal/oil)
- heating (oil)
- medical (patients)
- crematorium / cemetery (funerals)
- bathes (visitors)
- park (visitors)
- unique buildings and monuments (visitors)
- all (building upkeep)

**Comment by Sipke82** [comment]
Nice overview! 
Got no access to the game for a few weeks, but i think roads and stuff also show upkeep per week.

So are you gonna change to show the actually week stats (7 realtime days)?

**Comment by dymanoid** [comment]
Showing stats for a particular predefined period is not possible (be it an hour, a day, or a week). The reason of that is how the game does calculate the statistics. The game calculates all stats every 3840 simulation frames regardless of what time flow **Real Time** configures. This leads to a very odd situation: all economy and logistics are based on this 3840 simulation frames period. Set the time flow speed to **7** - and one stats period is 80 minutes. Set the speed to **1** - and the stats period is one minute!

Since the statistics gathering is scattered across the whole game, it would be a nightmare trying to synchronize the calculation with the time flow speed. And keeping in mind that it can arbitrary change (and often)...

So instead, the statistics period will be shown, not the alternatively calculated values.

That means:

- on time speed **7** in **Real Time**, you will see _20 passengers in last 80 min._
- on time speed **1** it will be _20 passengers in last 1 min._

These are the same 20 passengers in the same time, but the calculation period was different (because of different time speed).

This also affects the economy (income / expense), upkeep costs, oil and coal storage, water consumption, etc. etc. You will see this new statistics period for all of those parameters, but the numbers will stay the same.
