### ISSUE TITLE
Bug? cim traveled to the industry --> teleports to his office workspot

### ISSUE THREAD

**Issue by Sipke82** [dymanoid/RealTime#72]
I was Snooping around in my industrial traffic, there i noticed a driver going to a industry. but it was a worker at a office! Still he parked his car at the industry. Quickly i started following him, and while he was walking out of his parked car, he teleported back to his house. and finally after a few seconds, he teleported to his work in the office, which is miles away from his house and the parked car at a industry plot!
Here an overview of  the area:

![image](https://user-images.githubusercontent.com/30873812/42835266-ab54165a-89f8-11e8-93ac-d6c87b15d9e9.png)

So i was wondering if this might be a effect of RT --> travelling of workers to their work. or perhaps TMPE related... what do you think?

**Comment by dymanoid** [comment]
**Real Time** doesn't teleport citizens that are visible (i.e. drive a car or walk around). The mod only teleports "virtual" citizens. So the second teleport could be caused by **Real Time**, if that citizen was selected to be "virtual" for the moment. But the first one - no way. The question without an answer is what the heck did this citizen want in the industry area. If his workplace was an office, then the only explanation I can imagine is that the TM:PE's pathfinding & parking search logic lead him to that location. **Real Time** cannot do that, it only tells the citizen "now go to your work building".

**Comment by Sipke82** [comment]
Lol, the working day is now passed, and he is walking to his car..

(he's taking Public transportation, which is gonna suck for him :-X )

**Comment by Sipke82** [comment]
Alight seems more related to TMPE Parking AI
