### ISSUE TITLE
School holidays

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#75]
Suddenly thousands of kids run amok, causing huge increase in park and commerce usage. FOR WEEKS!

Parents also more likely to take holidays during this period = industry/offices could suffer worker shortages.

Maybe implement as an event, as this could potentially allow players to define specific dates for the holiday (multi-day events FTW!). It would also allow multiple school holidays to be defined - eg. summer hols, xmas hols, and so on.

IMO it would be good to use events to define all kinds of holidays - not just for school breaks. It could evolve in to "holiday calendar" event definition mods in the workshop?

Would be nice to see cim info panel state they holiday (ideally naming the holiday, as defined by the event).

See also: #28

**Comment by dymanoid** [comment]
While this "seems" to be realistic, we should consider the following.

**Real Time** changes only the time flow, but not the citizens' lifecycle. That means, that a child might become an adult in, say, a week. Does it make any sense to introduce school holidays for a week? That would cause the fact that a single generation won't go to school at all. Actually, they become educated, but will not physically visit the school, not even once.

Furthermore, does it make any sense to define holidays, say, 4 times a year? With that slow time speed, a game year would may be pass in a real time year (because I suppose that only few players play each day and many-many hours at once). So what is the point of having some changes in the game only a couple time in a year?

**Comment by dymanoid** [comment]
If 1 game year would be "real", then the game would be unplayable with the low time speed **Real Time** provides. Will anybody wait 10 game years till a child gets educated and starts working? Surely no.

There are mods available that control the citizens aging. I guess the best option is to use them. Maybe I could implement some slight change to the default aging logic (but not the 2 years in 1 as you suggest). Something like 1 game week = 1 citizen's year. But in that case I will have to make **Real Time** incompatible with those mods like Citizen Lifecycle Rebalance for example.

**Comment by Sipke82** [comment]
I changed the lifespan modifier in WG life cycle mod to 9 (default =3). Perhaps I should figure out how many RealTime days a life take... Will report on that later. I think that this mod should not fiddle with these figures.

To obtain holiday feeling, how about this,:
We begin the concept of month weeks. So 1week of RealTime = 1 month
The kids have holiday in the  1"julyweek" and in the 1 Decemberweek. In addition a certain percentage of the workforce is on holiday in those 2 game weeks (60%?)

**Comment by dymanoid** [comment]
@aubergine10, is this feature in essence the same as #118?

**Comment by aubergine10** [comment]
Yes.

School holidays would be seasonal events.
