### ISSUE TITLE
Store settings independently for each city in its save game

### ISSUE THREAD

**Issue by dymanoid** [dymanoid/RealTime#89]
Currently, the mod's settings are global for the application and don't change on loading another games.
This should be changed. The settings should be stored in the save game and restored back on loading it.
A new game should be created with default settings.

**Comment by aubergine10** [comment]
I've started a couple of new maps since subbing RT and like the fact that the settings are global. There's a couple of mods I have that do per-game and I have to reconfig them each time which gets tiresome after a while.

If this is implemented, could there be an option to "use current settings as defaults for new games"?
